apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dnn
  janus-idp.io/tekton: dnn
  backstage.io/kubernetes-id: dnn
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dnn
resources:
- deployment.yaml
- route.yaml
- service.yaml
