apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dnn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dnn 
  name: dnn
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dnn
    weight: 100 
